### ISSUE TITLE
Add a statement on the release page explaining that there is a false positive reaction of antiviruses

### ISSUE THREAD

**Issue by loutre-un-jour** [dfint/installer#82] opened 2024-08-27 20:43 UTC
On the installer page, there are two links to VT analysis of the Linux and Windows 0.4.4 archives :
🛡 [VirusTotal GitHub Action](https://github.com/crazy-max/ghaction-virustotal) analysis:
    [dfint-installer-lin-0.4.4.tar.gz](https://www.virustotal.com/gui/file-analysis/ZjhiYmVjZGNhZThiOWE0ZDMzMjcwNDU3M2VmNTkzODc6MTcyMzU2MjU2OQ==/detection)
    [dfint-installer-win-0.4.4.zip](https://www.virustotal.com/gui/file-analysis/YjRmZjM0YjRjYjkxODcwYjU0ODgyOGQ0YWIyYjQ4MjM6MTcyMzU2MjU3MA==/detection)

Windows link points to the analysis result and shows that two engines have issues with the file :
Google Detected
Ikarus Trojan.Win64.Hacktool

![Capture d'écran 2024-08-27 223721](https://github.com/user-attachments/assets/f0b2565d-fbae-4314-98bf-69d3df92cfe3)

I would expect either :
- VT saying that there is no virus
- a statement on the release explaining that there is a false positive due to [...] (probably the way the patching works)

**Comment by insolor** [comment] 2024-08-27 20:45
See FAQ: #58 

Duplicate of #27

**Comment by insolor** [comment] 2024-08-28 09:46
> a statement on the release explaining that there is a false positive due to [...] (probably the way the patching works)

...due to the reason, that they are just dumb. The installer doesn't patch anything, it just downloads data/files from the internet and replaces some files in the game's directory.

**Closed** 2024-08-28 10:04 UTC
