### ISSUE TITLE
There is no Chinese option in the dropdown menu

### ISSUE THREAD

**Issue by AllenLmz** [dfint/installer#57] opened 2024-05-22 03:29 UTC
How can I add a new language? I see that there is already a Chinese translation here

https://explore.transifex.com/dwarf-fortress-translation/dwarf-fortress-steam/

**Comment by insolor** [comment] 2024-05-22 05:19
@AllenLmz at the moment, the game itself doesn't support output of text with a hieroglyphic script. See the explanation here: https://github.com/dfint/df-steam-hook#supported-languages

**Comment by insolor** [comment] 2024-05-22 10:27
Duplicate of #32

**Closed by insolor** 2024-05-22 10:27 UTC
Labels: faq
